import { UserStory } from '@/types/story';

// Plain text format optimized for Word/Google Docs
export function formatStoryAsPlainText(story: UserStory): string {
  let text = 'USER STORY\n\n';
  
  // Story format - clean and readable
  text += `As a ${story.role}\n`;
  text += `I want ${story.goal}\n`;
  text += `So that ${story.benefit}\n\n`;
  
  // Acceptance Criteria
  text += 'ACCEPTANCE CRITERIA\n\n';
  
  story.acceptanceCriteria.forEach((criterion, index) => {
    if (criterion.type === 'given-when-then') {
      text += `${index + 1}. Given ${criterion.given}\n`;
      text += `   When ${criterion.when}\n`;
      text += `   Then ${criterion.then}\n\n`;
    } else {
      text += `${index + 1}. ${criterion.description}\n`;
    }
  });
  
  // Footer
  text += '\n---\nGenerated by User Story Spark\n';
  
  return text;
}

// Markdown format for file download
export function formatStoryAsMarkdown(story: UserStory): string {
  let markdown = '# User Story\n\n';
  
  // Story format
  markdown += `**As a** ${story.role}  \n`;
  markdown += `**I want** ${story.goal}  \n`;
  markdown += `**So that** ${story.benefit}\n\n`;
  
  // Acceptance Criteria
  markdown += '## Acceptance Criteria\n\n';
  
  story.acceptanceCriteria.forEach((criterion, index) => {
    if (criterion.type === 'given-when-then') {
      markdown += `### Scenario ${index + 1}\n`;
      markdown += `- **Given** ${criterion.given}\n`;
      markdown += `- **When** ${criterion.when}\n`;
      markdown += `- **Then** ${criterion.then}\n\n`;
    } else {
      markdown += `${index + 1}. ${criterion.description}\n`;
    }
  });
  
  // INVEST Score
  markdown += '\n## INVEST Quality Indicators\n\n';
  const invest = story.investScore;
  markdown += `- **Independent**: ${invest.independent ? '✓' : '✗'}\n`;
  markdown += `- **Negotiable**: ${invest.negotiable ? '✓' : '✗'}\n`;
  markdown += `- **Valuable**: ${invest.valuable ? '✓' : '✗'}\n`;
  markdown += `- **Estimable**: ${invest.estimable ? '✓' : '✗'}\n`;
  markdown += `- **Small**: ${invest.small ? '✓' : '✗'}\n`;
  markdown += `- **Testable**: ${invest.testable ? '✓' : '✗'}\n`;
  
  markdown += '\n---\n*Generated by User Story Spark*\n';
  
  return markdown;
}

export function downloadMarkdown(content: string, filename: string = 'user-story.md') {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}
